# Generated by Django 3.2.23 on 2023-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route',
            field=models.CharField(choices=[('RE1', 'For example A'), ('RE2', 'For example B')], default='RE1', max_length=3),
        ),
    ]
